        *   *Issue:* `params` is declared inside the `if` block scope in some languages, but in Go, `:=` inside an `if` creates a new variable *unless* the variable was already declared outside. Here, `var params map[string]interface{}` is declared outside. However, `json.Unmarshal` takes a pointer. If `params` is nil, `Unmarshal` allocates a map.
        *   *Wait, looking closer at the code:*
            This is actually valid Go syntax. `params` is declared outside. `Unmarshal` takes `&params`. It modifies `params`.
            *However*, the error message says "references undefined variable 'params' in buildArcpyParams call (shadowed by local declaration)".
            Let's look at the snippet again.
            If the code was:
            Then `params` would be shadowed.
            But the provided code in the "GO_FILE===" block is:
            This looks correct. Why does the error say it's shadowed?
            Maybe the error description implies the *result* of the unmarshal logic is what's broken, or perhaps I need to ensure `params` is initialized if `paramsJSON` is empty?
            If `paramsJSON` is empty, `params` remains `nil`. `buildArcpyParams` handles `len(params) == 0`.
            Let's re-read the error carefully: "HandleArcGISProRunToolbox references undefined variable 'params' in buildArcpyParams call (shadowed by local declaration)".
            Perhaps the input code provided in the prompt text actually *had* the shadowing issue, but the text I'm reading in the "GO_FILE===" block looks okay?
            Let's look at the "Original code" block. It's cut off.
            Let's look at the "GO_FILE===" block again.
            Actually, `json.Unmarshal` into a `nil` map pointer works fine.
            Maybe the error is referring to a different version of the code or I am misinterpreting the "shadowed" part.
            *Hypothesis:* The error description might be slightly misleading or referring to a specific context where `params` wasn't declared correctly. However, looking at the code:
            `pyScript := fmt.Sprintf(..., buildArcpyParams(params))`
            If `params` is nil, `buildArcpyParams` receives nil.
            Let's look at `buildArcpyParams`:
            This handles nil maps (len is 0).
            *Wait*, if the error says "shadowed by local declaration", maybe the code *should* have been:
            Or maybe the error implies that `params` was declared *inside* the `if` in the broken version.
            Since I have to fix it, I will ensure `params` is declared at the function scope and populated correctly.
            The current code:
            This is valid Go. I will leave it as is, or perhaps initialize it to an empty map to be safe? No, `nil` is fine for `len`.
            *Self-Correction*: The error list is generated by "Reviewers". It might be hallucinating slightly on the *cause* (shadowing) but identifying the *symptom* (params issue). I will ensure the code is robust.

            import sys
            try:
                # List system toolboxes
                toolboxes = arcpy.ListToolboxes("*")
                for tb in sorted(toolboxes):
                    print(tb)
            except Exception as e:
                print(f"ERROR: {e}", file=sys.stderr)
                sys.exit(1)
            `
            switch exportFormat {
            case "PDF":
                exportFunc = fmt.Sprintf("layout.exportToPDF(r'%s')", outputPath)
            case "PNG", "JPEG", ...:
                exportFunc = fmt.Sprintf("layout.exportTo%s(r'%s')" , exportFormat, outputPath)
                }