   ... (broken code) ...
   package tools
   ... (second code block) ...
   ... (first code block) ...
   ... (first code block) ...
   package tools
   ... (second code block) ...
   ... (first code block) ...
   package tools
   ... (second code block) ...
   ... (first code block) ...
   package tools
   ... (second code block) ...
   ... (first code block) ...
   package tools
   ... (second code block) ...
   package tools

   import (
   	"context"
   	"encoding/json"
   	"fmt"
   	"net/http"
   	"net/url"
   	"strings"
   	"time"
   )

   var http.DefaultClient = http.DefaultClient

   func HandleSearchSkills(ctx context.Context, args map[string]interface{}) (ToolResponse, error) {
   	... (code) ...
   
	return ok("not yet implemented")
}

   func HandleGetSkillDetails(ctx context.Context, args map[string]interface{}) (ToolResponse, error) {
   	... (code) ...
   }